### DISCUSSION TITLE
Generator: Which configuration file do we need to use?

### DISCUSSION THREAD

**Discussion by samuel-duhaime** [chairemobilite/evolution#585] [Polls]
# Discussion

## Problems
Currently, the problem is that it's not possible to review an Excel file using GitHub, which makes it difficult to review all the changes using Generator. Additionally, it's challenging to have two people working on the same project with a Generator because the changes are in the cloud. This means that when someone makes a change in Excel, it affects everyone working on the project. We want to find a better solution for this.

## Possible solutions
We've discussed two possible configurations: 'csv' and 'yaml'. Each has pros and cons.

## YAML
For example, we could use a 'yaml' configuration. This is an example of a widget.

```yaml
widget: 
    questionName: home_dwellingType
    inputType: Radio
    active: true
    section: home
    path: home.dwellingType
    fr: Dans quel **type d'habitation ou de propriété** vivez-vous ?
    en: In what **type of dwelling or property** do you live?
    choices: dwellingType
    containsHtml: true
    customPath: home.dwellingTypeOther
    customChoice: other
```

Pros:

- Easy to understand
- Simple to use array values
- Easy to write for non-technical individuals
- No need to write unnecessary keys for the widget

Cons:

- Lacks types
- Quite verbose
- Difficult to change the keys to all the widgets
- Will require more time to make it work with Generator compared to 'csv'
- Challenging to compare one widget to another

## CSV

I don't think I need to provide an example. It's something that everyone knows.

Pros:
- Easy to convert Excel to CSV
- Concise
- Simple to update multiple labels simultaneously

Cons:
- Lacks types
- More challenging to work with array or object values
- The widgets may have numerous headers at some point if we want to support complex case with Generator
- More difficult to comprehend with big file
- Likely requires installation of an extension to work with Visual Studio

## Other Alternatives
We could consider using other alternatives such as 'JSON' or 'TypeScript'. Perhaps we don't need the configuration files to be uniform for everything. Alternatively, we could simulate some type checking with the generator and raise an error if the widget configuration is not well-written.

## Discussion
I believe it's crucial to gather everyone's input before launching the creation of OD_National.
